variable "aws_region" { type = string, default = "ap-south-1" }
variable "project_name" { type = string, default = "gitops-pilot" }
variable "environment" { type = string, default = "development" }
variable "cluster_version" { type = string, default = "1.31" }
variable "vpc_cidr" { type = string, default = "10.20.0.0/16" }
variable "node_instance_types" { type = list(string), default = ["t3.medium"] }
variable "node_min_size" { type = number, default = 2 }
variable "node_desired_size" { type = number, default = 2 }
variable "node_max_size" { type = number, default = 4 }
