apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-pilot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SrikanthManikandan38/gitops-pilot.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-pilot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
